##########################
## Site Config Settings ##
##########################

# Theme version
version: 2.0.1

author: 王峰
# 你的头像url
avatar: https://file.wf2311.com/wf2311.png
# avatar link
avatar_link: /
# 头像背景图
brand: /img/brand.jpg
# favicon
favicon: https://file.wf2311.com/favicon.ico

# Header
menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: 书单
    directory: books/
    icon: fa-book
  - page: rss
    directory: atom.xml
    icon: fa-rss

## sub menu
#submenu:
#  - page: 技术
#    directory: categories/技术
#    icon: fa-right
#  - page: 工作
#    directory: categories/工作
#    icon: fa-right
#  - page: 生活
#    directory: categories/生活
#    icon: fa-right
#  - page: 杂记
#    directory: categories/杂记
#    icon: fa-right

# Sidebar
widgets:
  - info
  - recent_posts
  - category
  - tag
  - archive
#  - weibo
#  - links
#  - reward

#打赏
reward:
  enable: true  #是否开启打赏，关闭设为false
  title: 如果觉得我的文章对您有帮助，请随意打赏。
  wechat: https://file.wf2311.com/wechat_pay.png     #微信，关闭设为 false
  alipay: https://file.wf2311.com/alipay.png     #支付宝，关闭设为 false

# Toc
toc:
  enable: true
  number: false

highlight_theme: pale night

# Static files
js: js
css: css
stylesheets:
- /css/index.css
scripts:
- /js/utils.js
#- /js/fancybox.js
- /js/copy.js
#- /js/fireworks.js
#- /js/transition.js
#- /js/scroll.js
- /js/common.js

# cdn for third-party library
# ---------------
cdn:
  css:
    fontawesome: https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css
    fancybox: https://cdn.bootcss.com/fancybox/3.5.6/jquery.fancybox.min.css
  js:
#    anime: /js/third-party/anime.min.js
#    jquery: /js/third-party/jquery.min.js
#    fancybox: /js/third-party/jquery.fancybox.min.js
#    velocity: /js/third-party/velocity.min.js
#    velocity-ui: /js/third-party/velocity.ui.min.js
    anime: https://cdn.bootcss.com/animejs/2.2.0/anime.min.js
    jquery: https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js
    fancybox: https://cdn.bootcss.com/fancybox/3.5.6/jquery.fancybox.min.js
    velocity: https://cdn.bootcss.com/velocity/1.5.2/velocity.min.js
    velocity-ui: https://cdn.bootcss.com/velocity/1.5.2/velocity.ui.min.js

# mermaid chart see https://github.com/webappdevelp/hexo-filter-mermaid-diagrams
mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: true  # default true
  version: "7.1.2" # default v7.1.2
  options:  # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
  #startOnload: true  // default true

# Date_formats
date_formats:
  archive: "MM月DD日"
  category: "YYYY/MM/DD"
  post: "YYYY-MM-DD"
  tag: "YYYY-MM"

# Extensions
Plugins:
  hexo-generator-feed
  hexo-generator-sitemap
  hexo-generator-baidu-sitemap

#Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20

#sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

#Local search
local_search: true ## Use a javascript-based local search engine, true/false.

#Cmments
comment:
  duoshuo: #chaooo ## duoshuo_shortname
  disqus: ## disqus_shortname
#  livere: MTAyMC8zNDY0OC8xMTE4NQ== ## 来必力(data-uid)
  uyan: ## 友言(uid)
  cloudTie: ## 网易云跟帖(productKey)
  changyan: ## 畅言需在下方配置两个参数，此处不填。
    appid: cyteanoMa
    appkey: prod_27ac74f72c70e7240b5f924ef92bae6a

#Share
self_share: true
baidu_share: false ## 百度分享
JiaThis_share: ##true ##JiaThis分享
duoshuo_share: #true ##true 多说分享必须和多说评论一起使用。
addToAny_share: false # AddToAny share. Empty list hides. List items are service name at url. For ex: email for '<a href="https://www.addtoany.com/add_to/email?linkurl=...'
#  - twitter
#  - baidu
#  - facebook
#  - google_plus
#  - linkedin
#  - email

# Analytics
google_analytics: UA-85417096-1 ## Your Google Analytics tracking id, e.g. UA-42025684-2
baidu_analytics: 97500f623f8c7cc9c77569130121cfa6 ## Your Baidu Analytics tracking id, e.g. 1006843030519956000

# Miscellaneous
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
widgets_on_small_screens: true ## Set to true to enable widgets on small screens.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.


info:
  items:
#  - label: podcast
#    title: 网站
#    url: https://wangfeng.pro
#    content: https://wangfeng.pro
  - label: envelope
    title: 邮箱
    url: mailto:work@wangfeng.pro
    content: work@wangfeng.pro
  - label: github
    title: Github
    url: https://github.com/wf2311
    content: https://github.com/wf2311
  - label: git
    title: 码云
    url: https://gitee.com/wf2311
    content: https://gitee.com/wf2311
  - label: weixin
    title: 微信
    url:
    content: wf_2311
    image: https://file.wf2311.com/wechat.jpeg
  - label: qq
    title: QQ
    url:
    content: 836219767
    image: https://file.wf2311.com/qq.jpeg
  - label: weibo
    title: 微博
    url: https://weibo.com/wangfengpro
    content: wf2311
since: 2017
icp:
  text: 鄂ICP备15002386号
  url: https://www.miitbeian.gov.cn/

# Links widget. Empty links will hide widget.
links:
  - title: 灰灰博客
    url: https://liuyueyi.github.io/hexblog/
  - title: site-name2
    url: http://www.example2.com/
  - title: site-name3
    url: http://www.example3.com/
